```{r}
hcg <-  read.table("../data/w.data")
colnames(hcg) = c("id","year", "doctco", "age", 
                  "male","educ","married","hsize", 
                  "sport", "goodh", "badh", "sozh", 
                  "loginc", "ft", "pt", "unemp", 
                  "winter", "spring", "fall")

selected_row_names_vec <- c('Age', 'Age^2', 'Male', 'Education', 'Married', 
                   'Househould size', 'Active Sport', 
                   'Good health', 'Bad health', 
                   'Social assistance', 'Log(income)', 
                   'Year=1996', 'Year=1997', 'Year=1998', 'Year=1999')
```

```{r}
emp_vec <- c()
for (idx in seq(dim(hcg)[1])){
  if(hcg[[idx, 'ft']] == 1)
    emp_vec <- c(emp_vec, 'full-time')
  else if (hcg[[idx, 'pt']] == 1)
    emp_vec <- c(emp_vec, 'part-time')
  else if (hcg[[idx, 'unemp']] == 1)
    emp_vec <- c(emp_vec, 'unemployed')
  else
    emp_vec <- c(emp_vec, 'self-employed')
}
```


```{r}
data_df <- hcg %>% 
  tibble() %>%
  mutate(age2=age^2) %>%
  mutate(emp=factor(emp_vec)) %>%
  dplyr::select(id, doctco, age, age2, male, educ, married, hsize, sport, 
         goodh, badh, emp, sozh, loginc, year, winter, spring, fall)
```

## Column 1: Pooled Poisson Regression

```{r}
model_fit <- glm(
  doctco~age+age2+factor(male)+educ+factor(married)+hsize+
    factor(sport)+factor(goodh)+factor(badh)+factor(sozh)+
    loginc+factor(year)+
    factor(emp)+factor(winter)+factor(spring)+factor(fall), 
  family = "poisson", data = data_df)

cov_mat <- vcovHC(model_fit, type = "HC0")
std_err <- sqrt(diag(cov_mat))
q_val <- qnorm(0.975)

pool_df <- cbind(
  Estimate = coef(model_fit)
  , "Robust SE" = std_err
  , z = (coef(model_fit)/std_err)
  , "Pr(>|z|) "= 2 * pnorm(abs(coef(model_fit)/std_err), lower.tail = FALSE)
  , LL = coef(model_fit) - q_val  * std_err
  , UL = coef(model_fit) + q_val  * std_err
)
```

```{r}
res_df_col1 <- pool_df[seq(2, 16), ]
rownames(res_df_col1) <- selected_row_names_vec
res_df_col1
```  

```{r}
logLik(model_fit)
```

```{r}
nobs(model_fit)
```


## Column 2: Panel Poisson Regression with Random Effects
```{r}
model_fit <- pglm(
  doctco~age+age2+factor(male)+educ+factor(married)+hsize+factor(sport)+
    factor(goodh)+factor(badh)+factor(sozh)+
    loginc+factor(year)+
    factor(emp)+factor(winter)+factor(spring)+factor(fall),
  model = "random",
  family = "poisson",
  index=c("id"),
  data = data_df
  )
```

```{r}
res_df_col2 <- cbind(coefficients(summary(model_fit)), confint(model_fit))[seq(2, 16), ]
rownames(res_df_col2) <- selected_row_names_vec
res_df_col2
```

```{r}
summary(model_fit)$loglik[1]
```
## Column 3: Panel Poisson Regression with Fixed Effects

```{r}
model_fit <- pglm(
  doctco~factor(married)+hsize+factor(sport)+
    factor(goodh)+factor(badh)+factor(sozh)+
    loginc+factor(year)+
    factor(emp)+factor(winter)+factor(spring)+factor(fall), 
    model = "within",
    family = "poisson",
    index=c("id"),
    data = data_df
    )
```

```{r}
partial_rowname <- selected_row_names_vec[seq(5, 15)]
res_df_col3 <- cbind(coefficients(summary(model_fit)), confint(model_fit))[seq(11), ]
rownames(res_df_col3) <- partial_rowname
res_df_col3
```

```{r}
summary(model_fit)$loglik[1]
```

Export the calculations
```{r}
col_1 <- res_df_col1[,c("Estimate", "Robust SE")]
write.csv(col_1, "../out/table-2-pooled.csv")

col_2 <- res_df_col2[,c("Estimate", "Std. error")]
colnames(col_2) <- c("Estimate", "Robust SE")
write.csv(col_2, "../out/table-2-random.csv")

col_3 <- res_df_col3[,c("Estimate", "Std. error")]
colnames(col_3) <- c("Estimate", "Robust SE")
write.csv(col_3, "../out/table-2-fixed.csv")
```


```{r}
col_1
```
```{r}
    col_2 %>%
    data.frame() %>%
    tibble::rownames_to_column()
```

```{r}
col_1 %>%
  data.frame() %>%
  tibble::rownames_to_column(var = 'index') %>%
  rename(`Pooled Estimate`=`Estimate`, 
         `Pooled Robust SE`=`Robust.SE`) %>%
  left_join(
    col_2 %>%
    data.frame() %>%
    tibble::rownames_to_column(var = 'index') %>%
    rename(`Random Effects Estimate`=`Estimate`, 
           `Random Effects Robust SE`=`Robust.SE`),
    by='index'
  ) %>%
    left_join(
    col_3 %>%
    data.frame() %>%
    tibble::rownames_to_column(var = 'index') %>%
    rename(`Fixed Effects Estimate`=`Estimate`, 
           `Fixed Effects Robust SE`=`Robust.SE`),
    by='index'
  ) %>% 
  column_to_rownames(var = 'index') %>%
  write.csv("../out/table-2.csv")
```

